id: I839D9DEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T20:33:50+00:00'
last_modified: '2022-06-08T02:47:18.499814+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21756
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་གྱི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    95BF:
      image_group_id: I1KG21853
      title: ''
      total_pages: 266
      order: 1
      base_file: 95BF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
