id: P005396
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21756
  title: མཁའ་འགྲོ་ཡེ་ཤེས་མཚོ་རྒྱལ་གྱི་རྣམ་ཐར།
  author: ''
  volumes:
    5ab08110d3724928971175a6ac6ae89b:
      image_group_id: I1KG21853
      title: ''
      volume_number: 1
      total_pages: 266
